function HospitalActivityFeed() {

  return (

    <section className="dashboard-panel live-feed-panel section-gap">


      <div className="panel-header">

        <div>

          <span>
            LIVE OPERATIONS
          </span>


          <h2>
            Operational Activity Feed
          </h2>


          <p>
            Recent language access events generated by
            the OpenLEP monitoring engine.
          </p>


        </div>




        <div className="feed-live">

          <span></span>

          Live

        </div>


      </div>





      <div className="activity-feed">



        <div className="activity-item critical">


          <time>
            11:42
          </time>


          <div>

            <strong>
              Emergency Department
            </strong>


            <p>
              Spanish interpreter demand exceeded
              operational threshold.
            </p>


          </div>


          <span>
            Attention
          </span>


        </div>






        <div className="activity-item warning">


          <time>
            11:15
          </time>


          <div>

            <strong>
              Arabic Video Services
            </strong>


            <p>
              Additional interpreter assigned to reduce
              response time.
            </p>


          </div>


          <span>
            Resolved
          </span>


        </div>






        <div className="activity-item success">


          <time>
            10:58
          </time>


          <div>

            <strong>
              Response SLA
            </strong>


            <p>
              Average response returned below the
              hospital target.
            </p>


          </div>


          <span>
            Healthy
          </span>


        </div>






        <div className="activity-item neutral">


          <time>
            09:41
          </time>


          <div>

            <strong>
              Complaint Resolution
            </strong>


            <p>
              Language access complaint successfully closed.
            </p>


          </div>


          <span>
            Closed
          </span>


        </div>



      </div>


    </section>

  );

}


export default HospitalActivityFeed;